In [1]:
from math import cos, sin, radians

In [2]:
import scipy
import pprint
import scipy.linalg

In [3]:
def LUdecompy(A):
    n = lem(A)
    for k in range(0, n-1):
        for i in range(k_1,n):
            if A[i,k] !=0.0:
                lam = a [i,k]/A[k,k]
                A[i,k+1:n] = A[i,k+1:n] - lam*A[k,k+1:n]
                A[i,k] = lam
    return A

In [4]:
def LUsolve(A,B):
    n = len(A)
    for k in range(1,n):
        B[k] = b[k] - dot(A[k,0:k],b[0:k])
    for k in range(n-1,-1,-1):
        B[k] = (B[k] - dot(A[k,k+1:n],B[k+1:n]))/A[k,k]
    return B

In [5]:
r30 = radians(30)
r60 = radians(60)
print("30 degrees = {0} radians".format(r30))
print("60 degrees = {0} radians".format(r60))

30 degrees = 0.5235987755982988 radians
60 degrees = 1.0471975511965976 radians


In [6]:
A = scipy.array([[cos(r30), 0, -sin(r30), 0, 0, 0], [sin(r30), 0, cos(r30), 0, 0, 0], [-cos(r30), -1, 0, -1, 0, 0], [-sin(r30), 0, 0, 0, -1, 0], [0, 1, sin(r30), 0, 0, 0], [0, 0, cos(r30), 0, 0, -1]])
P, L, U = scipy.linalg.lu(A)

print ("A:")
pprint.pprint(A)

print ("P:")
pprint.pprint(P)

print ("L:")
pprint.pprint(L)

print ("U:")
pprint.pprint(U)

A:
array([[ 0.8660254,  0.       , -0.5      ,  0.       ,  0.       ,  0.       ],
       [ 0.5      ,  0.       ,  0.8660254,  0.       ,  0.       ,  0.       ],
       [-0.8660254, -1.       ,  0.       , -1.       ,  0.       ,  0.       ],
       [-0.5      ,  0.       ,  0.       ,  0.       , -1.       ,  0.       ],
       [ 0.       ,  1.       ,  0.5      ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.8660254,  0.       ,  0.       , -1.       ]])
P:
array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])
L:
array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [-1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.57735027, -0.        ,  1.        ,  0.        ,  0.        ,
      

In [7]:
scipy.set_printoptions(formatter={'float': '{: 0.2}'.format})
A

array([[ 0.87,  0.0, -0.5,  0.0,  0.0,  0.0],
       [ 0.5,  0.0,  0.87,  0.0,  0.0,  0.0],
       [-0.87, -1.0,  0.0, -1.0,  0.0,  0.0],
       [-0.5,  0.0,  0.0,  0.0, -1.0,  0.0],
       [ 0.0,  1.0,  0.5,  0.0,  0.0,  0.0],
       [ 0.0,  0.0,  0.87,  0.0,  0.0, -1.0]])

In [11]:
#To input values, change values in the B array below
B = scipy.array([1000, 0, 1000, 0, 0, 0]) #F1x, F1y, F2x, F2y, F3x, F3y
xNames = ['F1', 'F2', 'F3', 'H2', 'V2', 'V3']

In [12]:
xScipy = scipy.around(scipy.linalg.solve(A,B).reshape(6,1),2)
xDiv = scipy.matmul(scipy.linalg.inv(A),B)
print(xDiv,xScipy)

[ 8.7e+02  2.5e+02 -5e+02 -2e+03 -4.3e+02 -4.3e+02] [[ 8.7e+02]
 [ 2.5e+02]
 [-5e+02]
 [-2e+03]
 [-4.3e+02]
 [-4.3e+02]]


In [13]:
for i in zip(xNames, xDiv, xScipy):
    print('{0} = {1} = {2}' .format(i[0], i[1], i[2][0]))

F1 = 866.0254037844387 = 866.03
F2 = 249.99999999999991 = 250.0
F3 = -499.9999999999999 = -500.0
H2 = -2000.0 = -2000.0
V2 = -433.0127018922193 = -433.01
V3 = -433.0127018922193 = -433.01
